### ISSUE TITLE
OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by skarekrow** [g2p/bedup#23]
I decided to run this on my Arch Desktop and this is the error I get. The log spits this out at the end.

-------------------------
```
File 'home/brandon/.local/share/akonadi/db_data/ib_logfile0' is in use, skipping
File 'home/brandon/.local/share/akonadi/db_data/ib_logfile1' is in use, skipping
01.91 Size group 14/47 sampled 33 hashed 11 freed 0
Traceback (most recent call last):
  File "/usr/bin/bedup", line 9, in <module>
    load_entry_point('bedup==0.9.0', 'console_scripts', 'bedup')()
  File "/usr/lib/python3.3/site-packages/bedup/__main__.py", line 491, in script_main
    sys.exit(main(sys.argv))
  File "/usr/lib/python3.3/site-packages/bedup/__main__.py", line 480, in main
    return args.action(args)
  File "/usr/lib/python3.3/site-packages/bedup/__main__.py", line 199, in vol_cmd
    dedup_tracked(sess, volset, tt, defrag=args.defrag)
  File "/usr/lib/python3.3/site-packages/bedup/tracking.py", line 399, in dedup_tracked
    dedup_tracked1(ds, ofile_reserved, query)
  File "/usr/lib/python3.3/site-packages/bedup/tracking.py", line 590, in dedup_tracked1
    dedup_fileset(ds, fileset, fd_names, fd_inodes, size)
  File "/usr/lib/python3.3/site-packages/bedup/tracking.py", line 613, in dedup_fileset
    if clone_data(dest=dfd, src=sfd, check_first=True):
  File "/usr/lib/python3.3/site-packages/bedup/platform/btrfs.py", line 601, in clone_data
    ioctl_pybug(dest, lib.BTRFS_IOC_CLONE, src)
  File "/usr/lib/python3.3/site-packages/bedup/platform/btrfs.py", line 360, in ioctl_pybug
    return fcntl.ioctl(fd, ioc, arg)
OSError: [Errno 22] Invalid argument
```
----------------------------

Any idea? It deduped some files and then started chocking on akonadi. I haven't had one issue with it running on my server with identical setup (minus KDE and linux-ck kernel).

**Comment by olifre** [comment]
Please have a look at https://github.com/g2p/bedup/issues/61#issuecomment-120753743 , maybe one of the to-be-deduplicated files is marked as nodatacow (you can check with strace and lsattr as described in my comment)? 
I think in that case bedup should not fatal out, but continue and skip this file.
