### ISSUE TITLE
str/bytes errors on Python 3

### ISSUE THREAD

**Issue by spitfire** [g2p/bedup#27]
```
# bedup dedup /
Traceback (most recent call last):
  File "/usr/lib64/python3.2/posixpath.py", line 80, in join
    if b.startswith(sep):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/bedup-python3.2", line 9, in <module>
    load_entry_point('bedup==0.9.0', 'console_scripts', 'bedup')()
  File "/usr/lib64/python3.2/site-packages/bedup/__main__.py", line 487, in script_main
    sys.exit(main(sys.argv))
  File "/usr/lib64/python3.2/site-packages/bedup/__main__.py", line 476, in main
    return args.action(args)
  File "/usr/lib64/python3.2/site-packages/bedup/__main__.py", line 147, in vol_cmd
    [volpath], tt, recurse=True)
  File "/usr/lib64/python3.2/site-packages/bedup/filesystem.py", line 590, in load_vols
    lo, sta = vol._fs._load_visible_vols([volpath], nest_desc=True)
  File "/usr/lib64/python3.2/site-packages/bedup/filesystem.py", line 274, in _load_visible_vols
    os.path.join(start_desc.description, relpath),
  File "/usr/lib64/python3.2/posixpath.py", line 91, in join
    raise TypeError("Can't mix strings and bytes in path components.")
TypeError: Can't mix strings and bytes in path components.

# uname -a
Linux server01 3.11.0-rc3 #4 SMP Sat Aug 3 16:01:01 Local time zone must be set--see zic m x86_64 Intel(R) Core(TM)2 Duo CPU E8400 @ 3.00GHz GenuineIntel GNU/Linux

# cat /usr/src/linux/.config |grep -i btrfs
CONFIG_BTRFS_FS=y
CONFIG_BTRFS_FS_POSIX_ACL=y
# CONFIG_BTRFS_FS_CHECK_INTEGRITY is not set
# CONFIG_BTRFS_FS_RUN_SANITY_TESTS is not set
# CONFIG_BTRFS_DEBUG is not set

/dev/sda on / type btrfs (rw,noatime,compress=zlib,space_cache,autodefrag)
```

**Comment by g2p** [comment]
I think I fixed this in 5007c0363b8d3423f8b5c7677bf0d0babd5d4a25. Sorry for the delay.
