### ISSUE TITLE
bedup.filesystem.NotMounted on crypted root

### ISSUE THREAD

**Issue by man0lis** [g2p/bedup#33]
```
# bedup dedup /
Traceback (most recent call last):
  File "/root/.virtualenvs/bedup/bin/bedup", line 9, in <module>
    load_entry_point('bedup==0.9.0', 'console_scripts', 'bedup')()
  File "/root/.virtualenvs/bedup/lib/python3.3/site-packages/bedup/__main__.py", line 483, in script_main
    sys.exit(main(sys.argv))
  File "/root/.virtualenvs/bedup/lib/python3.3/site-packages/bedup/__main__.py", line 472, in main
    return args.action(args)
  File "/root/.virtualenvs/bedup/lib/python3.3/site-packages/bedup/__main__.py", line 150, in vol_cmd
    [volpath], tt, recurse=True)
  File "/root/.virtualenvs/bedup/lib/python3.3/site-packages/bedup/filesystem.py", line 580, in load_vols
    if vol.root_info.path != b'/':
  File "/root/.virtualenvs/bedup/lib/python3.3/site-packages/bedup/filesystem.py", line 314, in root_info
    return self._fs.root_info[self._impl.root_id]
  File "/root/.virtualenvs/bedup/lib/python3.3/site-packages/sqlalchemy/util/langhelpers.py", line 618, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/root/.virtualenvs/bedup/lib/python3.3/site-packages/bedup/filesystem.py", line 189, in root_info
    raise NotMounted
bedup.filesystem.NotMounted
```

root filesystem is encrypted using cryptsetup/luks with device mapper
mounted filesystems:

```
/dev/mapper/root  on  /                                 type  btrfs        (rw,noatime,compress=lzo,ssd,noacl,space_cache)
proc              on  /proc                             type  proc         (rw,nosuid,nodev,noexec,relatime)
tmpfs             on  /run                              type  tmpfs        (rw,nosuid,nodev,relatime,size=1612472k,mode=755)
udev              on  /dev                              type  devtmpfs     (rw,nosuid,relatime,size=10240k,nr_inodes=2014531,mode=755)
mqueue            on  /dev/mqueue                       type  mqueue       (rw,nosuid,nodev,noexec,relatime)
devpts            on  /dev/pts                          type  devpts       (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
shm               on  /dev/shm                          type  tmpfs        (rw,nosuid,nodev,noexec,relatime)
sysfs             on  /sys                              type  sysfs        (rw,nosuid,nodev,noexec,relatime)
debugfs           on  /sys/kernel/debug                 type  debugfs      (rw,nosuid,nodev,noexec,relatime)
cgroup_root       on  /sys/fs/cgroup                    type  tmpfs        (rw,nosuid,nodev,noexec,relatime,size=10240k,mode=755)
fusectl           on  /sys/fs/fuse/connections          type  fusectl      (rw,nosuid,nodev,noexec,relatime)
openrc            on  /sys/fs/cgroup/openrc             type  cgroup       (rw,nosuid,nodev,noexec,relatime,release_agent=/lib64/rc/sh/cgroup-release-agent.sh,name=openrc)
cpuset            on  /sys/fs/cgroup/cpuset             type  cgroup       (rw,nosuid,nodev,noexec,relatime,cpuset)
cpu               on  /sys/fs/cgroup/cpu                type  cgroup       (rw,nosuid,nodev,noexec,relatime,cpu)
cpuacct           on  /sys/fs/cgroup/cpuacct            type  cgroup       (rw,nosuid,nodev,noexec,relatime,cpuacct)
devices           on  /sys/fs/cgroup/devices            type  cgroup       (rw,nosuid,nodev,noexec,relatime,devices)
freezer           on  /sys/fs/cgroup/freezer            type  cgroup       (rw,nosuid,nodev,noexec,relatime,freezer)
bfqio             on  /sys/fs/cgroup/bfqio              type  cgroup       (rw,nosuid,nodev,noexec,relatime,bfqio)
/dev/mapper/root  on  /mnt/btrfs                        type  btrfs        (rw,noatime,compress=lzo,ssd,noacl,space_cache)
/dev/mapper/root  on  /home/manolis/do-not-backup       type  btrfs        (rw,noatime,compress=lzo,ssd,noacl,space_cache)
/dev/mapper/root  on  /home/manolis/Downloads           type  btrfs        (rw,noatime,compress=lzo,ssd,noacl,space_cache)
tmpfs             on  /tmp                              type  tmpfs        (rw,relatime,size=2097152k)
tmpfs             on  /var/tmp/portage                  type  tmpfs        (rw,relatime,size=8388608k)
binfmt_misc       on  /proc/sys/fs/binfmt_misc          type  binfmt_misc  (rw,nosuid,nodev,noexec,relatime)
```

uname -a

```
Linux hyperion 3.12.0-gentoo #2 SMP Tue Nov 19 23:40:46 CET 2013 x86_64 Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz GenuineIntel GNU/Linux
```

grep BTRFS /usr/src/linux/.config

```
CONFIG_BTRFS_FS=y
# CONFIG_BTRFS_FS_POSIX_ACL is not set
# CONFIG_BTRFS_FS_CHECK_INTEGRITY is not set
# CONFIG_BTRFS_FS_RUN_SANITY_TESTS is not set
# CONFIG_BTRFS_DEBUG is not set
# CONFIG_BTRFS_ASSERT is not set
```

**Comment by g2p** [comment]
For anyone hitting this issue:
As a workaround, you could run dedup without arguments or with a filesystem id.
