### ISSUE TITLE
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.

### ISSUE THREAD

**Issue by Nefelim4ag** [g2p/bedup#38]
uname -rv:           3.13.6-1-ARCH #1 SMP PREEMPT Fri Mar 7 22:47:48 CET 2014
python --version: Python 3.3.5
Distribution:         Arch Linux
---
00.00 Committing tracking stateException closing connection <sqlite3.Connection object at 0x7ff5bef498f0>
Traceback (most recent call last):
  File "/usr/lib/python3.3/site-packages/sqlalchemy/pool.py", line 536, in _finalize_fairy
    fairy._reset(pool, echo)
  File "/usr/lib/python3.3/site-packages/sqlalchemy/pool.py", line 666, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/lib/python3.3/site-packages/sqlalchemy/engine/default.py", line 395, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 140693399103232 and this is thread id 140693533701888

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.3/site-packages/sqlalchemy/pool.py", line 243, in _close_connection
    self._dialect.do_close(connection)
  File "/usr/lib/python3.3/site-packages/sqlalchemy/engine/default.py", line 401, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 140693399103232 and this is thread id 140693533701888
00.03 Committing tracking state

**Comment by voidzero** [comment]
Nice. Well done.

**Comment by mahdidavoodi7** [comment]
me tooooo

**Comment by tarek421995** [comment]
thank you
