### ISSUE TITLE
In-memory database runs out of disk

### ISSUE THREAD

**Issue by dowlingw** [g2p/bedup#43]
Runtime environment:
bedup at commit `80cb217d4819a03e159e42850a9a3f14e2b278a3`
kernel: `
Linux 3.11.0-15-generic #25-Ubuntu SMP Thu Jan 30 17:22:01 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`
btrfs-tools version: `3.12-1`

Running bedup across the following filesystem:
````
# df -h /mnt/new/
Filesystem      Size  Used Avail Use% Mounted on
/dev/md1         15T   12T  3.1T  79% /mnt/new
# btrfs filesystem df /mnt/new/
Data, single: total=12.35TiB, used=11.73TiB
System, DUP: total=8.00MiB, used=1.31MiB
System, single: total=4.00MiB, used=0.00
Metadata, DUP: total=18.00GiB, used=17.08GiB
Metadata, single: total=8.00MiB, used=0.00
````

Generates the following trace and error:

````
01:33:58 Size group 1600/4229 sampled 5273 hashed 1644 freed 332461279880
Traceback (most recent call last):
  File "./bedup", line 9, in <module>
    load_entry_point('bedup==0.9.0', 'console_scripts', 'bedup')()
  File "/root/.local/lib/python2.7/site-packages/bedup/__main__.py", line 483, in script_main
    sys.exit(main(sys.argv))
  File "/root/.local/lib/python2.7/site-packages/bedup/__main__.py", line 472, in main
    return args.action(args)
  File "/root/.local/lib/python2.7/site-packages/bedup/__main__.py", line 198, in vol_cmd
    dedup_tracked(sess, volset, tt, defrag=args.defrag)
  File "/root/.local/lib/python2.7/site-packages/bedup/tracking.py", line 394, in dedup_tracked
    dedup_tracked1(ds, ofile_reserved, query)
  File "/root/.local/lib/python2.7/site-packages/bedup/tracking.py", line 446, in dedup_tracked1
    for comm1 in query:
  File "/root/.local/lib/python2.7/site-packages/bedup/tracking.py", line 326, in __iter__
    inodes_by_size = groupby(inodes, lambda inode: inode.size)
  File "/root/.local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2398, in __iter__
    return self._execute_and_instances(context)
  File "/root/.local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2413, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/root/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 717, in execute
    return meth(self, multiparams, params)
  File "/root/.local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 317, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/root/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 814, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/root/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 927, in _execute_context
    context)
  File "/root/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1076, in _handle_dbapi_exception
    exc_info
  File "/root/.local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 185, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/root/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 920, in _execute_context
    context)
  File "/root/.local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 425, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (OperationalError) database or disk is full u'SELECT "Inode".vol_id AS "Inode_vol_id", "Inode".ino AS "Inode_ino", "Inode".size AS "Inode_size", "Inode"
.mini_hash AS "Inode_mini_hash", "Inode".fiemap_hash AS "Inode_fiemap_hash", "Inode".has_updates AS "Inode_has_updates" \nFROM "Inode", (SELECT "Inode".vol_id AS vol_id, "Inode".ino AS
ino, "Inode".size AS size, "Inode".mini_hash AS mini_hash, "Inode".fiemap_hash AS fiemap_hash, "Inode".has_updates AS has_updates \nFROM "Inode" \nWHERE "Inode".vol_id IN (?)) AS filter
ed JOIN (SELECT filtered.size AS size, count(*) AS inode_count, max(filtered.has_updates) AS has_updates \nFROM (SELECT "Inode".vol_id AS vol_id, "Inode".ino AS ino, "Inode".size AS siz
e, "Inode".mini_hash AS mini_hash, "Inode".fiemap_hash AS fiemap_hash, "Inode".has_updates AS has_updates \nFROM "Inode" \nWHERE "Inode".vol_id IN (?)) AS filtered \nWHERE filtered.size
 <= ? GROUP BY filtered.size \nHAVING inode_count > ? AND has_updates > ? ORDER BY -filtered.size\n LIMIT ? OFFSET ?) AS s1 ON s1.size = "Inode".size ORDER BY -"Inode".size, "Inode".ino
' (1, 1, 51856166, 1, 0, 200, 0)
````

**Comment by g2p** [comment]
I forgot this bug when closing #42, but I think this is fixed. Reopen if not.
