### ISSUE TITLE
bedup.filesystem.NotPlugged Error

### ISSUE THREAD

**Issue by stratbasher** [g2p/bedup#51]
Hello,

I've installed BTRFS on my External Hard Drive and was hoping to use bedup for deduplication. I'm running Ubuntu Server 14.04.1, kernel version 3.16.0-031600-generic, and python version 2.7.6. Upon running "sudo bedup scan /ext/path/to/directory" or "sudo bedup scan uuid-here", I get this error and stacktrace....

```
Traceback (most recent call last):
  File "/usr/local/bin/bedup", line 9, in <module>
    load_entry_point('bedup==0.9.0', 'console_scripts', 'bedup')()
  File "/home/adam/.local/lib/python2.7/site-packages/bedup-0.9.0-py2.7-linux-x86_64.egg/bedup/__main__.py", line 487, in script_main
    sys.exit(main(sys.argv))
  File "/home/adam/.local/lib/python2.7/site-packages/bedup-0.9.0-py2.7-linux-x86_64.egg/bedup/__main__.py", line 476, in main
    return args.action(args)
  File "/home/adam/.local/lib/python2.7/site-packages/bedup-0.9.0-py2.7-linux-x86_64.egg/bedup/__main__.py", line 147, in vol_cmd
    [volpath], tt, recurse=True)
  File "/home/adam/.local/lib/python2.7/site-packages/bedup-0.9.0-py2.7-linux-x86_64.egg/bedup/filesystem.py", line 584, in load_vols
    vol = self._get_vol_by_path(volpath, desc=VolDesc(volpath, True))
  File "/home/adam/.local/lib/python2.7/site-packages/bedup-0.9.0-py2.7-linux-x86_64.egg/bedup/filesystem.py", line 424, in _get_vol_by_path
    return self._get_vol(fd, desc)
  File "/home/adam/.local/lib/python2.7/site-packages/bedup-0.9.0-py2.7-linux-x86_64.egg/bedup/filesystem.py", line 443, in _get_vol
    fs = self.get_fs(uuid=fs_uuid)
  File "/home/adam/.local/lib/python2.7/site-packages/bedup-0.9.0-py2.7-linux-x86_64.egg/bedup/filesystem.py", line 398, in get_fs
    raise NotPlugged(uuid)
```

That's as far as I can get. Is this related to #26 ?

**Comment by g2p** [comment]
FWIW, this is similar to #33 and may have the same workaround.

**Comment by ptman** [comment]
I'm getting NotPlugged when running bedup scan with either mount path or uuid

**Comment by muggenhor** [comment]
I have the same problem. Both with mount path and UUID. Not using any path finishes within 2.4 seconds and I'm not seeing any size differences (and am expecting some, because I've got several Debian LXC containers on this system with quite some file overlap).

I'm running this from within a LXC Debian Stretch container on an OpenWRT (armhf) host. The root subvolume is mounted within that container, so perfectly accessible.
