### ISSUE TITLE
'ascii' codec can't encode characters in position 81-82: ordinal not in range(128)

### ISSUE THREAD

**Issue by alphaonex86** [g2p/bedup#53]
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.3/bedup", line 9, in <module>
    load_entry_point('bedup==0.9.0', 'console_scripts', 'bedup')()
  File "/usr/lib/python3.3/site-packages/bedup/__main__.py", line 487, in script_main
    sys.exit(main(sys.argv))
  File "/usr/lib/python3.3/site-packages/bedup/__main__.py", line 476, in main
    return args.action(args)
  File "/usr/lib/python3.3/site-packages/bedup/__main__.py", line 68, in cmd_find_new
    find_new(volume_fd, args.generation, sys.stdout, terse=args.terse, sep=sep)
  File "/usr/lib/python3.3/site-packages/bedup/platform/btrfs.py", line 704, in find_new
    sh.transid, item.transid, item.type, fsdecode(name), sep))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 81-82: ordinal not in range(128)

**Comment by g2p** [comment]
I think this happens when your console locale is ascii? I've never seen this, so I assume having an UTF-8 locale fixes it. Distros should take care of this.

**Comment by g2p** [comment]
This page explains it: http://click.pocoo.org/5/python3/#python-3-surrogate-handling
