### ISSUE TITLE
exits with sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread

### ISSUE THREAD

**Issue by unhammer** [g2p/bedup#63]
After running a dedup --defrag /home, and deduping a bunch, it ended with:

    01:57:30 Size group 2129/2129 sampled 5023 hashed 4847 freed 70275323717
    00.00 Committing tracking stateException during reset or similar
    Traceback (most recent call last):
      File "/usr/lib/python3.5/site-packages/sqlalchemy/pool.py", line 636, in _finalize_fairy
        fairy._reset(pool)
      File "/usr/lib/python3.5/site-packages/sqlalchemy/pool.py", line 776, in _reset
        pool._dialect.do_rollback(self)
      File "/usr/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 420, in do_rollback
        dbapi_connection.rollback()
    sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 140443502655232 and this is thread id 140443647022848
    Exception closing connection <sqlite3.Connection object at 0x7fbb8d1b09d0>
    Traceback (most recent call last):
      File "/usr/lib/python3.5/site-packages/sqlalchemy/pool.py", line 636, in _finalize_fairy
        fairy._reset(pool)
      File "/usr/lib/python3.5/site-packages/sqlalchemy/pool.py", line 776, in _reset
        pool._dialect.do_rollback(self)
      File "/usr/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 420, in do_rollback
        dbapi_connection.rollback()
    sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 140443502655232 and this is thread id 140443647022848
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/lib/python3.5/site-packages/sqlalchemy/pool.py", line 290, in _close_connection
        self._dialect.do_close(connection)
      File "/usr/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 426, in do_close
        dbapi_connection.close()
    sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 140443502655232 and this is thread id 140443647022848
    00.51 Committing tracking state

**Comment by unhammer** [comment]
using 0.9.0-5 on arch linux btw

**Comment by g2p** [comment]
Please ask the AUR maintainer to update, this bug is fixed in the latest release.
