### ISSUE TITLE
AttributeError: 'MigrationContext' object has no attribute '_ensure_version_table'

### ISSUE THREAD

**Issue by matwey** [g2p/bedup#65]
Hello, I am running bedup 0.10.0 from pypi and facing the following issue:

```
# bedup show
Traceback (most recent call last):
  File "/usr/bin/bedup", line 9, in <module>
    load_entry_point('bedup==0.10.0', 'console_scripts', 'bedup')()
  File "/usr/lib64/python3.4/site-packages/bedup/__main__.py", line 495, in script_main
    sys.exit(main(sys.argv))
  File "/usr/lib64/python3.4/site-packages/bedup/__main__.py", line 484, in main
    return args.action(args)
  File "/usr/lib64/python3.4/site-packages/bedup/__main__.py", line 73, in cmd_show_vols
    sess = get_session(args)
  File "/usr/lib64/python3.4/site-packages/bedup/__main__.py", line 103, in get_session
    upgrade_schema(engine)
  File "/usr/lib64/python3.4/site-packages/bedup/migrations.py", line 39, in upgrade_schema
    context._ensure_version_table()
AttributeError: 'MigrationContext' object has no attribute '_ensure_version_table'
```

* Python 3.4.1
* alembic 0.6.0
* cffi 0.8.6
* SQLAlchemy 1.0.7

**Comment by ilezcano** [comment]
Same here. Might have something to do with recent changes to alembic. I remember reading similar problems.

**Comment by matwey** [comment]
```setup.py``` says the following:
```

install_requires = [
    'alembic',  # XXX I need Alembic, but not Mako or MarkupSafe.
    'cffi >= 0.4.2',
    # Requiring this version to get rid of lextab/yacctab
    # files dumped in random places
    'pycparser >= 2.9.1',
    'pyxdg',
    'SQLAlchemy >= 0.8.2', # needs Query.select_entity_from()
]
```
It means that no version for alembic is specified. It would be great either fix ```setup.py``` or fix the issue.
