### ISSUE TITLE
Runtime error on Ubuntu 15.10

### ISSUE THREAD

**Issue by hobbyhorse** [g2p/bedup#67]
I am trying to run bedup on a machine that I am testing and am getting the following:

root@backups:~# pip3 list
alembic (0.8.3)
bedup (0.10.0)
cffi (1.3.0)
chardet (2.3.0)
colorama (0.3.3)
command-not-found (0.3)
html5lib (0.999)
language-selector (0.1)
Mako (1.0.3)
MarkupSafe (0.23)
pip (1.5.6)
pycparser (2.14)
pycurl (7.19.5.1)
pygobject (3.16.2)
python-apt (1.0.1)
python-debian (0.1.27)
python-editor (0.4)
pyxdg (0.25)
requests (2.7.0)
setuptools (18.4)
six (1.9.0)
SQLAlchemy (1.0.9)
ssh-import-id (4.5)
ufw (0.34)
unattended-upgrades (0.1)
urllib3 (1.11)
wheel (0.26.0)
root@backups:~# uname -a
Linux backups 4.2.0-16-generic #19-Ubuntu SMP Thu Oct 8 15:35:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
root@backups:~# bedup dedup /mnt/newfs/
Traceback (most recent call last):
  File "/usr/local/bin/bedup", line 9, in <module>
    load_entry_point('bedup==0.10.0', 'console_scripts', 'bedup')()
  File "/usr/local/lib/python3.5/dist-packages/bedup/__main__.py", line 495, in script_main
    sys.exit(main(sys.argv))
  File "/usr/local/lib/python3.5/dist-packages/bedup/__main__.py", line 484, in main
    return args.action(args)
  File "/usr/local/lib/python3.5/dist-packages/bedup/__main__.py", line 148, in vol_cmd
    [volpath], tt, recurse=True)
  File "/usr/local/lib/python3.5/dist-packages/bedup/filesystem.py", line 578, in load_vols
    if vol.root_info.path != '/':
  File "/usr/local/lib/python3.5/dist-packages/bedup/filesystem.py", line 319, in root_info
    return self._fs.root_info[self._impl.root_id]
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/langhelpers.py", line 747, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/usr/local/lib/python3.5/dist-packages/bedup/filesystem.py", line 193, in root_info
    return read_root_tree(fd)
  File "/usr/local/lib/python3.5/dist-packages/bedup/platform/btrfs.py", line 545, in read_root_tree
    for (root_id, ri) in ri_rel.items():
RuntimeError: dictionary changed size during iteration

Any thoughts or suggestions?

**Comment by hobbyhorse** [comment]
I have moved over to CentOS and will not be able to test any solutions to this problem. Closing.
