### ISSUE TITLE
bedup show fails after upgrade to 0.10

### ISSUE THREAD

**Issue by rvandegrift** [g2p/bedup#69]
After upgrading to 0.10:

```
$ sudo bedup show
Label: backup UUID: 766797ba-762c-41af-ae29-9d33e4c4c1e7
  Device: /dev/mapper/backup
Traceback (most recent call last):
  File "/usr/local/bin/bedup", line 9, in <module>
    load_entry_point('bedup==0.10.0', 'console_scripts', 'bedup')()
  File "/usr/local/lib/python3.4/dist-packages/bedup/__main__.py", line 495, in script_main
    sys.exit(main(sys.argv))
  File "/usr/local/lib/python3.4/dist-packages/bedup/__main__.py", line 484, in main
    return args.action(args)
  File "/usr/local/lib/python3.4/dist-packages/bedup/__main__.py", line 75, in cmd_show_vols
    show_vols(whole_fs, args.fsuuid_or_device, args.show_deleted)
  File "/usr/local/lib/python3.4/dist-packages/bedup/filesystem.py", line 707, in show_vols
    show_fs(fs, print_indented, show_deleted)
  File "/usr/local/lib/python3.4/dist-packages/bedup/filesystem.py", line 619, in show_fs
    root_ids.update(fs.root_info.keys())
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/langhelpers.py", line 725, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/usr/local/lib/python3.4/dist-packages/bedup/filesystem.py", line 193, in root_info
    return read_root_tree(fd)
  File "/usr/local/lib/python3.4/dist-packages/bedup/platform/btrfs.py", line 545, in read_root_tree
    for (root_id, ri) in ri_rel.items():
RuntimeError: dictionary changed size during iteration
```

**Comment by rvandegrift** [comment]
This is a duplicate of https://github.com/g2p/bedup/issues/78
