### ISSUE TITLE
error: ‘FS_DIRECTIO_FL’ undeclared

### ISSUE THREAD

**Issue by svenstaro** [g2p/bedup#77]
This is on Arch Linux with Python 3.5.1 and gcc 6.1.1. I get the following error while running the setup:

```
bedup/platform/__pycache__/_cffi__xb9e8bdx27bf31f9.c: In function ‘_cffi_check_struct_btrfs_data_container’:
bedup/platform/__pycache__/_cffi__xb9e8bdx27bf31f9.c:767:25: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
   { uint64_t(*tmp)[0] = &p->val; (void)tmp; }
                         ^
bedup/platform/__pycache__/_cffi__xc6fe055xd70c2778.c: In function ‘_cffi_const_FS_DIRECTIO_FL’:
bedup/platform/__pycache__/_cffi__xc6fe055xd70c2778.c:272:30: error: ‘FS_DIRECTIO_FL’ undeclared (first use in this function)
   o = _cffi_from_c_int_const(FS_DIRECTIO_FL);
                              ^
bedup/platform/__pycache__/_cffi__xc6fe055xd70c2778.c:72:8: note: in definition of macro ‘_cffi_from_c_int_const’
     (((x) > 0) ?                                                         \
        ^
bedup/platform/__pycache__/_cffi__xc6fe055xd70c2778.c:272:30: note: each undeclared identifier is reported only once for each function it appears in
   o = _cffi_from_c_int_const(FS_DIRECTIO_FL);
                              ^
bedup/platform/__pycache__/_cffi__xc6fe055xd70c2778.c:72:8: note: in definition of macro ‘_cffi_from_c_int_const’
     (((x) > 0) ?                                                         \
        ^
bedup/platform/__pycache__/_cffi__xc6fe055xd70c2778.c: In function ‘_cffi_const_FS_ECOMPR_FL’:
bedup/platform/__pycache__/_cffi__xc6fe055xd70c2778.c:314:30: error: ‘FS_ECOMPR_FL’ undeclared (first use in this function)
   o = _cffi_from_c_int_const(FS_ECOMPR_FL);
                              ^
bedup/platform/__pycache__/_cffi__xc6fe055xd70c2778.c:72:8: note: in definition of macro ‘_cffi_from_c_int_const’
     (((x) > 0) ?                                                         \
        ^
Traceback (most recent call last):
  File "/usr/lib/python3.5/distutils/unixccompiler.py", line 116, in _compile
    extra_postargs)
  File "/usr/lib/python3.5/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/lib/python3.5/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/lib/python3.5/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/cffi/ffiplatform.py", line 55, in _build
    dist.run_command('build_ext')
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.5/site-packages/setuptools/command/build_ext.py", line 49, in run
    _build_ext.run(self)
  File "/usr/lib/python3.5/distutils/command/build_ext.py", line 338, in run
    self.build_extensions()
  File "/usr/lib/python3.5/distutils/command/build_ext.py", line 447, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.5/distutils/command/build_ext.py", line 472, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/lib/python3.5/site-packages/setuptools/command/build_ext.py", line 174, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr/lib/python3.5/distutils/command/build_ext.py", line 532, in build_extension
    depends=ext.depends)
  File "/usr/lib/python3.5/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/lib/python3.5/distutils/unixccompiler.py", line 118, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 71, in <module>
    ext_modules=get_ext_modules(),
  File "/home/svenstaro/.cache/pacaur/bedup/src/bedup-0.10.0/bedup/platform/cffi_support.py", line 57, in get_ext_modules
    return [mod.ffi.verifier.get_extension() for mod in get_mods()]
  File "/home/svenstaro/.cache/pacaur/bedup/src/bedup-0.10.0/bedup/platform/cffi_support.py", line 49, in get_mods
    from . import (
  File "/home/svenstaro/.cache/pacaur/bedup/src/bedup-0.10.0/bedup/platform/chattr.py", line 69, in <module>
    ''')
  File "/home/svenstaro/.cache/pacaur/bedup/src/bedup-0.10.0/bedup/platform/cffi_support.py", line 45, in verify
    return ffi.verify(source, **kwargs)
  File "/usr/lib/python3.5/site-packages/cffi/api.py", line 450, in verify
    lib = self.verifier.load_library()
  File "/usr/lib/python3.5/site-packages/cffi/verifier.py", line 113, in load_library
    self._compile_module()
  File "/usr/lib/python3.5/site-packages/cffi/verifier.py", line 210, in _compile_module
    outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
  File "/usr/lib/python3.5/site-packages/cffi/ffiplatform.py", line 29, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose)
  File "/usr/lib/python3.5/site-packages/cffi/ffiplatform.py", line 62, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.ffiplatform.VerificationError: CompileError: command 'gcc' failed with exit status 1

```

**Comment by g2p** [comment]
Fixed, I think. Thank you.
