### ISSUE TITLE
 No such file or directory blkid

### ISSUE THREAD

**Issue by igroykt** [g2p/bedup#80]
Traceback (most recent call last):
  File "/bin/bedup", line 11, in <module>
    load_entry_point('bedup==0.10.1', 'console_scripts', 'bedup')()
  File "/root/.local/lib/python3.4/site-packages/bedup-0.10.1-py3.4-linux-x86_64.egg/bedup/__main__.py", line 497, in script_main
    sys.exit(main(sys.argv))
  File "/root/.local/lib/python3.4/site-packages/bedup-0.10.1-py3.4-linux-x86_64.egg/bedup/__main__.py", line 486, in main
    return args.action(args)
  File "/root/.local/lib/python3.4/site-packages/bedup-0.10.1-py3.4-linux-x86_64.egg/bedup/__main__.py", line 127, in vol_cmd
    vols = whole_fs.load_all_writable_vols(tt)
  File "/root/.local/lib/python3.4/site-packages/bedup-0.10.1-py3.4-linux-x86_64.egg/bedup/filesystem.py", line 557, in load_all_writable_vols
    for (uuid, di) in self.device_info.items():
  File "/root/.local/lib/python3.4/site-packages/SQLAlchemy-1.1.0b3-py3.4-linux-x86_64.egg/sqlalchemy/util/langhelpers.py", line 754, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/root/.local/lib/python3.4/site-packages/bedup-0.10.1-py3.4-linux-x86_64.egg/bedup/filesystem.py", line 489, in device_info
    subp = subprocess.Popen(cmd, stdout=subprocess.PIPE, universal_newlines=True)
  File "/usr/lib64/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'blkid'

which blkid
/sbin/blkid

cmd=bedup dedup

**Comment by igroykt** [comment]
Changed crontab task to run from /root/.local/bin instead of symlink (/usr/bin). That solved the problem.
